version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - network1
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=example@example.org" #FIXME
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    networks:
      - network1
    volumes:
      - omekas_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME

  omekas:
    depends_on:
      - omekas_db
    image: giocomai/omeka-s-docker:v4.1.1.production
    container_name: omekas
    restart: unless-stopped
    environment:
      MYSQL_USER: secretstring #FIXME
      MYSQL_PASSWORD: secretpassword #FIXME
      MYSQL_DATABASE: secretstring #FIXME
      MYSQL_HOST: omekas_db
      APPLICATION_ENV: production
      OMEKA_THEME_URL: https://github.com/omeka-s-themes/default/releases/download/v1.9.1/theme-default-v1.9.1.zip
    networks:
      - network1
    links:
      - omekas_db:omekas_db
    volumes:
      - omekas:/var/www/html/volume:Z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omekas.rule=Host(`example.com`)" #FIXME
      - "traefik.http.routers.omekas.entrypoints=websecure"
      - "traefik.http.routers.omekas.tls.certresolver=myhttpchallenge"
      - "traefik.docker.network=network1"

volumes:
  omekas_db:
  omekas:

networks:
  network1:
    external: true
