services:

  omekas:
    image: ghcr.io/erseco/omeka-s-docker:master
    build: .
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - omekas_data:/var/www/html/volume:Z
      - ../omeka-s-HelpAssistant:/var/www/html/volume/modules/HelpAssistant
      - ../omeka-s-theme-freedom-ate:/var/www/html/themes/freedom-ate
    environment:
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
      MYSQL_HOST: mariadb
      APPLICATION_ENV: development
      OMEKA_THEMES: 
      OMEKA_MODULES: |
        https://github.com/Daniel-KM/Omeka-S-module-Common/releases/download/3.4.74/Common-3.4.74.zip      
        https://github.com/Daniel-KM/Omeka-S-module-EasyAdmin/releases/download/3.4.29/EasyAdmin-3.4.29.zip
        https://github.com/Daniel-KM/Omeka-S-module-Adminer/releases/download/3.4.5-4.8.4/Adminer-3.4.5-4.8.4.zip
        https://github.com/omeka-s-modules/CSSEditor/releases/download/v1.3.1/CSSEditor-1.3.1.zip
        https://github.com/Daniel-KM/Omeka-S-module-Log/releases/download/3.4.27/Log-3.4.27-php-8.2.zip
        https://github.com/Daniel-KM/Omeka-s-module-AdvancedResourceTemplate/releases/download/3.4.49/AdvancedResourceTemplate-3.4.49.zip
        https://github.com/Daniel-KM/Omeka-s-module-BulkExport/releases/download/3.4.36/BulkExport-3.4.36.zip
        https://github.com/omeka-s-modules/CustomVocab/releases/download/v2.0.2/CustomVocab-2.0.2.zip
        https://github.com/ateeducacion/omeka-s-IsolatedSites/releases/download/v1.0.3/IsolatedSites-v1.0.3.zip
        https://github.com/Daniel-KM/Omeka-s-module-DerivativeMedia/releases/download/3.4.12/DerivativeMedia-3.4.12.zip
        https://github.com/ateeducacion/omeka-s-DiskQuota/releases/download/v1.0.1/DiskQuota-v1.0.1.zip
        https://github.com/omeka-s-modules/FacetedBrowse/releases/download/v1.7.0/FacetedBrowse-1.7.0.zip
        https://github.com/ateeducacion/omeka-s-ThreeDViewer/releases/download/v1.0.4/ThreeDViewer-v1.0.4.zip
        https://github.com/ateeducacion/omeka-s-GlobalLandingPage/releases/download/v1.0.1/GlobalLandingPage-v1.0.1.zip
        https://github.com/Daniel-KM/Omeka-S-module-GuestPrivate/releases/download/3.4.7/GuestPrivate-3.4.7.zip
        https://github.com/ateeducacion/OmekaS-LearningObject/releases/download/v1.0.0/LearningObjectAdapter-v1.0.0.zip
        https://github.com/Daniel-KM/Omeka-s-module-BlockPlus/releases/download/3.4.40/BlockPlus-3.4.40.zip



      OMEKA_PATH: /var/www/html
      PHP_POST_MAX_SIZE: 30M
      PHP_UPLOAD_MAX_FILESIZE: 30M

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

volumes:
  mariadb_data:
  omekas_data: